$ANSIBLE_VAULT;1.1;AES256
64363934363334623835333831646630666431373636323938613661326365393133383035396536
6339623762323139663039663937616531613032383332610a353066333733373033326434383565
63656561393961323235333730623162653537306338666162666635333165656331323631333763
3337393637376534640a393137363964626337626662393863343739663531363562313432613366
65336166373732333766306662316464303436376330386336626463343066346366613263663633
38636161653434356561323638376465663738633336343062383633323562336437333939633261
66383635376430393562636137336239633634303936326136633239393065316239323435643334
31396161326563393564383836373831633834396430646539373462346633623236613139663536
62396131333534666666316437653437343936323631333534653830346262316536383232653561
36396264636564373466303563323531396130306662613933616231643930613732383737366439
36393130363064313636666462626238316562663835346537356634326463643966386639396337
30366138646132333961363363383562353732343466333666366330303265323862343863636635
61396133646564343038663939346536366635376436323064393433343233623566333234666432
34303131383665623938343965343362666265383861393861656563333232326565313366376231
39346632633635663631336337663035623730343430323363323433353034626462646134643938
36316630303537323134
