---
- name: Create mongo directory
  ansible.builtin.file:
    path: "{{ mongo_deploy_path }}"
    state: directory
    mode: "0755"

- name: Template .env
  ansible.builtin.template:
    src: env.j2
    dest: "{{ mongo_deploy_path }}/.env"
    mode: "0600"
  notify: Restart mongo

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ mongo_deploy_path }}/docker-compose.yml"
    mode: "0644"
  notify: Restart mongo

- name: Ensure mongo is running
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: "{{ mongo_deploy_path }}"
  changed_when: false
