---
- name: Login to Docker Hub
  community.docker.docker_login:
    registry_url: "{{ docker_registry_url }}"
    username: "{{ vault_dockerhub_username }}"
    password: "{{ vault_dockerhub_password }}"
