---
- name: Check if Docker is installed
  ansible.builtin.command: docker --version
  register: docker_installed
  ignore_errors: true
  changed_when: false

- name: Check if Docker Compose is installed
  ansible.builtin.command: docker compose version
  register: docker_compose_installed
  ignore_errors: true
  changed_when: false

- name: Download Docker install script
  ansible.builtin.get_url:
    url: "{{ docker_install_script_url }}"
    dest: /tmp/get-docker.sh
    mode: "0755"
  when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

- name: Run Docker install script
  ansible.builtin.command: sh /tmp/get-docker.sh
  when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  when: docker_installed.rc != 0 or docker_compose_installed.rc != 0

- name: Ensure Docker is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
