- hosts: ovh-server
  become: yes
  pre_tasks:
    - name: Login to Docker Hub
      ansible.builtin.shell:
        cmd: echo "{{ vault_dockerhub_password }}" | docker login -u {{ vault_dockerhub_username }} --password-stdin
      no_log: true
  roles:
    - { role: portfolio, tags: portfolio }