- hosts: ovh-server
  become: yes
  pre_tasks:
    - name: Update apt cache (same as 'sudo apt update')
      apt:
        update_cache: yes
  roles:
    - { role: fail2ban, tags: hardening }
    - { role: docker, tags: docker }
    - { role: networks, tags: networks }
    - { role: monitoring, tags: monitoring }